### ISSUE TITLE
Please fail with KeyringError::NoBackendFound when there is no org.freedesktop.secrets available

### ISSUE THREAD

**Issue by argv-minus-one** [hwchen/secret-service-rs#14]
When there is no Secret Service implementation available (i.e. connecting to D-Bus was successful, but there is no `org.freedesktop.secrets` service), the error is `KeyringError::SecretServiceError(SsError::Dbus)`, where the `name` of the underlying `dbus::Error` is `org.freedesktop.DBus.Error.ServiceUnknown`.

In this situation, the keyring call should probably fail with `KeyringError::NoBackendFound` instead.

Failure to connect to D-Bus (because there is no session bus, and auto-starting it failed) should probably also result in `KeyringError::NoBackendFound`, but there doesn't appear to be a well-defined error name for that situation. Potential error names include `org.freedesktop.DBus.Error.NoServer`, `org.freedesktop.DBus.Error.FileNotFound`, or `org.freedesktop.DBus.Error.NotSupported` (not an exhaustive list).

**Comment by hwchen** [comment]
Thanks for looking into this! Having a `KeyringError::NoBackendFound` makes sense. Happy to take a PR, or I'll look into it when I have time.

**Comment by hwchen** [comment]
Finally realized that this probably belongs in keyring repo. At this moment it’s unlikely that I try to create more custom errors for dbus errors here.
