### ISSUE TITLE
Async API support

### ISSUE THREAD

**Issue by bilelmoussaoui** [hwchen/secret-service-rs#15]
It would be nice to have async API support

**Comment by hwchen** [comment]
Hi! I haven't thought too hard about this yet, as I've wanted to keep this crate relatively lightweight and simple.

Some things I'd want to think about:

- async would, at this moment, require commitment to either the `tokio` or `async-std` ecosystem for an executor.
- async support would also have to come from the `dbus` crate, whose own async story is in flux now. https://github.com/diwic/dbus-rs/issues/218

If we do figure out the async stuff, though, this would also be a good time to do a major refactor to bring the debus dependency up to date.

So, I'm not sure I want to take any action at this moment, I'd want to wait until the dust settles a bit first.

It would be also helpful if you could describe a particular use case for async, a blocking interface is probably sufficient for most people.

Anyways, I'll be leaving this issue open to track developments.

**Comment by BrainBlasted** [comment]
There's also the `glib` executors to consider as well.
