### ISSUE TITLE
Allow changing of dbus name?

### ISSUE THREAD

**Issue by Restioson** [hwchen/secret-service-rs#18]
When trying to run a flatpak'd application, this crate will fail with `unable to store token: SecretServiceError(Dbus(D-Bus error: org.freedesktop.DBus.Error.ServiceUnknown (org.freedesktop.DBus.Error.ServiceUnknown)))` if the application is not allowed to talk to the host secrets dbus. Flatpak does, however, provide a local dbus portal which stores the keychain on the application side (see https://github.com/flatpak/xdg-desktop-portal/) for more. Would it be possible to allow configuring the dbus name to something other than the default? In this case, it would be `org.freedesktop.portal.secrets`, or similar.

**Comment by hwchen** [comment]
Sounds reasonable, I'll take a look at the best way to make the change.

For reference, constants are defined here:
https://github.com/hwchen/secret-service-rs/blob/e771b8bbffb2520428d7011414b24bfc171c85b6/src/ss.rs#L11

And names should be initialized here: https://github.com/hwchen/secret-service-rs/blob/83933758aba0656db2a8c795ac4780c4e3c21a8d/src/lib.rs#L225

Not sure if `lazy_static` is something I can use to make the transition easier. I'll take a look.

**Comment by Restioson** [comment]
Maybe for backwards-compatibility there could be a function that takes a DBus name (etc), but the default `new` could use the default one.

**Comment by hwchen** [comment]
That sounds like a good way to do it.

**Comment by hwchen** [comment]
Just want to let you know that this is still on my radar, but I'm a bit busy at the moment; it might be a little while until I get to this (a few weeks).

**Comment by flyingpimonster** [comment]
If I understand correctly, this won't solve the problem. org.freedesktop.portal.Secret is a different API than org.freedesktop.Secrets.

The portal API provides a single secret which can be used to encrypt secrets inside the sandbox. Reasoning for this is given [in this blog post](https://blogs.gnome.org/mclasen/2019/10/03/some-flatpak-updates/).

**Comment by hwchen** [comment]
Ah, thanks for this info. I'm going to close this issue for now, since it doesn't look like there's anything actionable for me. Feel free to reopen if there's something I missed.
