### ISSUE TITLE
Providing the libsecret dbus api (secret-service-srv-rs?)

### ISSUE THREAD

**Issue by colemickens** [hwchen/secret-service-rs#19]
Hi. I want to modify https://github.com/cole-h/passrs to have a `passrs libsecret` command that would run a service providing the libsecret dbus service. This would require what I believe is the  the compliment to this project.

Is this something you have worked on, or are aware of someone working on?

**Comment by hwchen** [comment]
Hi! Sorry, I have not worked on a vault implementing the secret-service api. I only know of Gnome and KDE implementations which you may already be aware of: https://github.com/GNOME/gnome-keyring, https://github.com/KDE/kwallet
