### ISSUE TITLE
Switch crypto libraries.

### ISSUE THREAD

**Issue by alatiera** [hwchen/secret-service-rs#3]
`rust-crypto` is no longer maintained and the focus seems to have moved to [RustCrypto](https://github.com/RustCrypto).

**Comment by jhaye** [comment]
The usage of rust-crypto is especially problematic on specific mobile architectures by Intel like Cherrytrail, because rust-crypto relies on CPU instructuons not supported by them.

Related issue: https://github.com/DaGenix/rust-crypto/issues/391

**Comment by hwchen** [comment]
I do agree that switching from rust-crypto would be a good idea. I've had my issues with it in the past, I'll take a look at RustCrypto.

**Comment by hwchen** [comment]
Closed by #11
