### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by complexspaces** [hwchen/secret-service-rs#38]
Zbus 2.0 didn't end up coming as fast as I personally expected given the speed of the alpha releases (this is not a bad thing, though). However, I think it would be beneficial to publish a new release in order to do a few things for downstream users:

- Establish the higher MSRV and make it less of a surprise to anyone who updates later on.
- Remove deprecated dependencies (`aesni` and `aessoft`) from downstream user's trees.

This would probably be version `2.1.0`, as to avoid breaking anyone with a lower Rust compiler in a SemVer patch release.

@hwchen is this something you have time to look at soon?

**Comment by messense** [comment]
I've traced a outdated dependency to this crate, would also love a new release.

**Comment by complexspaces** [comment]
@hwchen friendly ping on this

**Comment by complexspaces** [comment]
@hwchen Another ping on this, sorry. We've updated to `zbus` 2.0 so it would be a good time to look at publishing an update.

**Comment by jeff-hiner** [comment]
@hwchen A ping from us as well for a deps update.

**Comment by complexspaces** [comment]
Sorry for the delay everyone. I spoke with Walther in private about this and sorted everything out. I'll make sure that a release is out by the end of the week 😄. Sorry for the delay and silence.

**Comment by hwchen** [comment]
Just want to give a big thanks to @complexspaces!

**Comment by unrelentingtech** [comment]
I would really appreciate a release with zbus 2. Currently switching to `secret-service = { git = "https://github.com/hwchen/secret-service-rs" }` is required to e.g. build [Fragments](https://gitlab.gnome.org/World/Fragments) on FreeBSD (as only zbus 2.x includes my portability patches).

**Comment by sophie-h** [comment]
For everyone using gtk-rs anyways, there are now bindings (i.e not rust native) for [libsecret available](https://gitlab.gnome.org/World/Rust/libsecret-rs).

**Comment by bilelmoussaoui** [comment]
Not wanting to step on anyone's toes here but I wrote a successor of secret-service-rs that is available at https://github.com/bilelmoussaoui/oo7. Still an alpha release but should work in most use cases

**Comment by moritzheiber** [comment]
In case you're looking for a dirty workaround, adding this to your `Cargo.toml` will override the potential dependency other crates are having towards `secret-service` (in particular, `keyring-rs`:

```toml

[patch.crates-io]
secret-service = { git = "https://github.com/hwchen/secret-service-rs" }
```

**Comment by bstrie** [comment]
I've also encountered the problem with the outdated nix dependency. @complexspaces @hwchen , any way I can help do some work here to unblock this?

**Comment by bstrie** [comment]
I've filed a PR bumping the version to 2.1.0: https://github.com/hwchen/secret-service-rs/pull/45 .

**Comment by complexspaces** [comment]
Hey there @bstrie, thanks for the putting the PR up.

I apologize for taking so long to get around to this. The conversation in #42 threw me off for quite a while and made me doubt some things. I've been kind of confused trying to figure out what the future of this crate is, especially now that `oo7` was released with async support. IMO, its internals are a lot cleaner then what `secret-service-rs` has today.

There seems to be (at least, in public) split between users who want a purely synchronous implementation and those who want `async`, following along with `zbus 2`. The downside of the later being, notably, that it requires a dependency on the `libdbus` C library. It just hasn't been high on my priority list to add that synchronous backend to accompany the `zbus` update.

With all that being said, if people still want to use this crate, I'd be happy to help get some updates merged and released while slowly working on the synchronous backend to "bring back" what some parties seem to be missing.

**Comment by messense** [comment]
Unfortunately 2.0.2 does not work for people indirectly depends on it via the keyring crate.

```bash
❯ cargo update -p secret-service --precise 2.0.2
    Updating crates.io index
error: failed to select a version for `bitflags`.
    ... required by package `nix v0.20.2`
    ... which satisfies dependency `nix = "^0.20.2"` of package `zbus v1.9.2`
    ... which satisfies dependency `zbus = "^1.9.2"` of package `secret-service v2.0.2`
    ... which satisfies dependency `secret-service = "^2.0.1"` of package `keyring v1.1.2`
    ... which satisfies dependency `keyring = "^1.1.2"` (locked to 1.1.2) of package `maturin v0.13.0-beta.7 (/Users/messense/Projects/maturin)`
versions that meet the requirements `>=1.1.0, <1.3.0` are: 1.2.1, 1.2.0, 1.1.0

all possible versions conflict with previously selected packages.

  previously selected package `bitflags v1.3.2`
    ... which satisfies dependency `bitflags = "^1.3.2"` of package `security-framework v2.6.1`
    ... which satisfies dependency `security-framework = "^2.6.1"` (locked to 2.6.1) of package `keyring v1.1.2`
    ... which satisfies dependency `keyring = "^1.1.2"` (locked to 1.1.2) of package `maturin v0.13.0-beta.7 (/Users/messense/Projects/maturin)`

failed to select a version for `bitflags` which could resolve this conflict
```

**Comment by bstrie** [comment]
Yes, next I want to see about getting the zbus folks to do a 1.9.3 release to bump their nix dependency to a more recent version in order to resolve the bitflags issue.

**Comment by bstrie** [comment]
@messense (and anyone else blocked by this issue), I've managed to convince the zbus maintainers to produce a 1.9.3 release that updates their nix dependency, so the bitflags issue should no longer be a problem.
