### ISSUE TITLE
Plan for crypto

### ISSUE THREAD

**Issue by hwchen** [hwchen/secret-service-rs#5]
There's a couple things I'd like to do to make the crypto side of this lib more robust for the future:
- remove dependency on unmaintained rust-crypto, hopefully upgrade to ring
- remove dependency on rand and move to ring for rng.
- rust-gmp is currently only used for powm. Consider implementing own powm to remove gmp dependency (do some performance comparison first)

The overall idea is to reduce dependencies, and to switch away from unmaintained libraries.

#3

**Comment by jhaye** [comment]
I just noticed that there is a crate available now on crates.io that seems to have good AES support: `aes_frast`. It is implemented in pure Rust, which might result in slightly worse performance but improved portability too.
I'll be looking into this in the coming days.

**Comment by hwchen** [comment]
Thanks for looking into this! I’m out of town until the end of June, but I’m excited to see what you find when I get back, and I’ll hopefully do a big refactor between this issue and #6 for powm.

**Comment by hwchen** [comment]
Closed by #11. I ended up going with RustCrypto
