### ISSUE TITLE
New major zbus release 4.0

### ISSUE THREAD

**Issue by VorpalBlade** [hwchen/secret-service-rs#71]
Just a heads up that you will need to update this crate to work with the new version. I know it was released just a few hours ago, so I don't want to seem impatient. This is just a heads up.

(I'm so looking forward to getting smaller binary sizes when I can avoid a ton of duplicated dependencies.)

**Comment by thewh1teagle** [comment]
I'm looking for that too, that's the only way I can use this library, since I got conflict with zbus 3 and Tauri.

**Comment by liff** [comment]
zbus 4 branch [here](https://github.com/liff/secret-service-rs/tree/zbus4) if you’d like to test.

**Comment by VorpalBlade** [comment]
No release made yet?

**Comment by complexspaces** [comment]
A new release with `zbus` 4.0 will be out soon.

**Comment by brotskydotcom** [comment]
Hey there @complexspaces, sorry to bother, but when do you expect a release that supports zbus 4.0? I have a lot of keyring clients asking me for it.

If it's not too much trouble, perhaps you could reopen this issue until you cut the release? That makes it easier for those of us waiting on it to track.

**Comment by complexspaces** [comment]
Thanks for the friendly poke 👍. `secret-service` 4.0 [has been released](https://crates.io/crates/secret-service/4.0.0) with the update. Please let me know if there's any issues.

**Comment by complexspaces** [comment]
It looks like I messed up the README's `Cargo.toml` example version, but that should be harmless.

**Comment by brotskydotcom** [comment]
Thanks for the release! Integrating now.
