### ISSUE TITLE
Cryptic error if no keychain exists

### ISSUE THREAD

**Issue by Rukenshia** [hwchen/secret-service-rs#8]
Hi,

while debugging a problem with a user we successfully reproduced the following behaviour on a new ubuntu machine:

When trying to get or set a password and no secrets have been set up so far (so no password for the default keychain has been set), the following error gets displayed:

```No such interface \'org.freedesktop.DBus.Properties'```

Reproduce steps:

1. Create a new VM using Ubuntu 16.04 LTS
2. Try setting or getting a password using this library (I use keychain-rs in [saml2aws-auto](https://github.com/Rukenshia/saml2aws-auto/releases) so you could run `saml2aws-auto groups add bla --role asdf --prefix asdf`, enter gibberish for URL, Username and Password and you'll see the error)
3. Setup a default keychain by using secret-tool (`secret-tool store --label="test" foo bar`)
4. Retry step 2 and it will work now

**Comment by hwchen** [comment]
Just wanted to let you know that I'm looking into this, but setting up a test environment is a bit of a pain at the moment.

**Comment by WGH-** [comment]
Should be fixed by #16

**Comment by clintfred** [comment]
I ran into this issue on kubuntu 16.04 using 1.1.0 (after #16) had been applied. I cloned the repo and was many of the tests were failing.

```
running 29 tests
test collection::test::should_delete_collection ... ignored
test collection::test::should_get_and_set_collection_label ... ignored
test collection::test::should_lock_and_unlock ... ignored
test collection::test::should_create_item ... ok
test item::test::should_lock_and_unlock ... ignored
test item::test::should_create_with_item_attributes ... FAILED
test test::should_create_and_delete_collection ... ignored
test collection::test::should_check_if_collection_locked ... FAILED
test collection::test::should_get_all_items ... FAILED
test collection::test::should_create_collection_struct ... FAILED
test item::test::should_create_and_get_secret ... FAILED
test item::test::should_create_and_delete_item ... FAILED
test collection::test::should_search_items ... FAILED
test item::test::should_check_if_item_locked ... FAILED
test item::test::should_get_and_set_item_attributes ... FAILED
test item::test::should_get_modified_created_props ... FAILED
test item::test::should_get_and_set_item_label ... FAILED
test item::test::should_get_secret_content_type ... FAILED
test session::test::should_create_plain_session ... ok
test item::test::should_set_secret ... FAILED
test test::should_create_secret_service ... ok
test test::should_get_collection_by_alias ... ok
test test::should_get_all_collections ... ok
test test::should_get_default_collection ... FAILED
test test::should_return_error_if_collection_doesnt_exist ... ok
test test::should_search_items ... FAILED
test test::should_get_any_collection ... ok
test session::test::should_create_encrypted_session ... ok
test item::test::should_create_and_get_secret_encrypted ... FAILED
```

After creating a default keychain using the `secret-tool` command from above, the tests all started passing.

**Comment by WGH-** [comment]
What I meant is that instead of returning a cryptic error, it returns a proper error now. I'm not sure that creating a default collection unconditionally should be this library's responsibility.

**Comment by clintfred** [comment]
You may be right. Perhaps this is just a documentation issue? Without this post I probably wouldn't  have figured out `NoResult` meant there wasn't a default collection.

**Comment by hwchen** [comment]
Sorry it was unclear, let me know what documentation would have made this clearer for you.

**Comment by hwchen** [comment]
Going to close this issue for now. Happy to take PRs that will clarify.
