### ISSUE TITLE
Compatibility with musl

### ISSUE THREAD

**Issue by konstin** [hwchen/secret-service-rs#9]
It seems that secret-service dynamically links system libraries, which means means you can't use keyring to create statically linked musl binaries:

```
ldd target/x86_64-unknown-linux-musl/debug/foo
        linux-vdso.so.1 (0x00007ffed8b6c000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f9abedeb000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f9abeb9e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9abe7ad000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9abe58e000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f9abe30a000)
        /lib/ld64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f9abf06c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9abe102000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f9abdedc000)
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f9abdcc0000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f9abd9a5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9abd7a1000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f9abd58c000)
```

Example main.rs, compiled with `cargo build --target x86_64-unknown-linux-musl`:

```rust
extern crate keyring;

use keyring::Keyring;

fn main() {
    let keyring = Keyring::new("foo", "bar");
    keyring.get_password();
}
```

It would be great if secret-service/keyring supported static linking.

**Comment by hwchen** [comment]
I think that the two system libs that need to be present currently are libgmp and libdbus. (correct me if I'm wrong; this is my understanding).

libgmp may be removed soon-ish, it shouldn't be necessary.

libdbus is a little trickier. See https://github.com/diwic/dbus-rs/issues/100. I have not yet checked out https://crates.io/crates/dbus-bytestream, which I've just seen is a native rust dbus implementation. But that might be a reasonable alternative. It would be a decent bit of work to swap dbus libs.

I definitely understand your desire to be able to statically link, though... it's something I'll work towards (slowly, for now).

**Comment by hwchen** [comment]
#11 removes the libgmp dependency

**Comment by hwchen** [comment]
#25 removes the need to link libdbus by switching to zbus. I think this should fix this issue.
